---
- name: Setup Jenkins Server
  hosts: jenkinsMachine
  become: yes
  tasks:
    - name: Update apt repository cache
      apt: update_cache=yes force_apt_get=yes

    - name: Install Java
      apt: name=openjdk-11-jdk state=present

    - name: Add Jenkins repository key
      apt_key:
        url: https://pkg.jenkins.io/debian/jenkins.io.key
        state: present

    - name: Add Jenkins repository
      apt_repository:
        repo: 'deb http://pkg.jenkins.io/debian-stable binary/'
        state: present

    - name: Install Jenkins
      apt: name=jenkins state=present

    - name: Start Jenkins service
      systemd:
        name: jenkins
        state: started
        enabled: yes
