---
- name: Setup Jenkins Server and EKS
  hosts: all
  become: yes
  tasks:
    - name: Update apt repository cache
      apt: update_cache=yes force_apt_get=yes

- name: Setup Jenkins Server
  hosts: jenkins
  become: yes
  tasks:
    - name: Install Java
      apt: name=openjdk-11-jdk state=present

    - name: Add Jenkins repository key
      apt_key:
        url: https://pkg.jenkins.io/debian/jenkins.io.key
        state: present

    - name: Add Jenkins repository
      apt_repository:
        repo: 'deb http://pkg.jenkins.io/debian-stable binary/'
        state: present

    - name: Install Jenkins
      apt: name=jenkins state=present

    - name: Start Jenkins service
      systemd:
        name: jenkins
        state: started
        enabled: yes

- name: Setup EKS Master Node
  hosts: eks
  become: yes
  tasks:
    - name: Install Docker
      apt: name=docker.io state=present

    - name: Install kubectl
      get_url:
        url: https://amazon-eks.s3.us-west-2.amazonaws.com/1.19.6/2021-01-05/bin/linux/amd64/kubectl
        dest: /usr/local/bin/kubectl
        mode: '0755'

    - name: Install aws-iam-authenticator
      get_url:
        url: https://amazon-eks.s3.us-west-2.amazonaws.com/1.19.6/2021-01-05/bin/linux/amd64/aws-iam-authenticator
        dest: /usr/local/bin/aws-iam-authenticator
        mode: '0755'
